//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int ID { get; set; }
        public string CustomerName { get; set; }
        public int ScheduleID { get; set; }
        public string FlightID { get; set; }
        public string SeatID { get; set; }
    
        public virtual Schedule Schedule { get; set; }
        public virtual Seat Seat { get; set; }
    }
}
